require('./dist/angular-datatables');
require('./dist/plugins/bootstrap/angular-datatables.bootstrap.js');
require('./dist/plugins/bootstrap/datatables.bootstrap.css');
require('./dist/plugins/colreorder/angular-datatables.colreorder.js');
require('./dist/plugins/columnfilter/angular-datatables.columnfilter.js');
require('./dist/plugins/light-columnfilter/angular-datatables.light-columnfilter.js');
require('./dist/plugins/colvis/angular-datatables.colvis.js');
require('./dist/plugins/fixedcolumns/angular-datatables.fixedcolumns.js');
require('./dist/plugins/fixedheader/angular-datatables.fixedheader.js');
require('./dist/plugins/scroller/angular-datatables.scroller.js');
require('./dist/plugins/tabletools/angular-datatables.tabletools.js');
require('./dist/plugins/buttons/angular-datatables.buttons.js');
require('./dist/plugins/select/angular-datatables.select.js');
module.exports = 'datatables';
